### ISSUE TITLE
Can't find e131 library used to build. 

### ISSUE THREAD

**Issue by SmAsH-jl** [grantHarris/raspberrypi-e131-led#3]
Can you link to the library you used for e131. 

pi@raspberrypi:~/raspberrypi-e131-led/Release $ cmake -DCMAKE_BUILD_TYPE=Release ..
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   log
--   program_options
--   date_time
--   log_setup
--   system
--   filesystem
--   thread
--   regex
--   chrono
--   atomic
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
E131
    linked by target "e131bridge" in directory /home/pi/raspberrypi-e131-led

-- Configuring incomplete, errors occurred!
See also "/home/pi/raspberrypi-e131-led/CMakeFiles/CMakeOutput.log".
See also "/home/pi/raspberrypi-e131-led/CMakeFiles/CMakeError.log".

**Comment by grantHarris** [comment]
https://github.com/hhromic/libe131
